Feat/graph view widget
ts4nfdi/terminology-service-suite pull request #155
Opened 2024-10-18 12:39 UTC by Pooya-Oladazimi

This is a basic implementation for the graph view. I could not transfer one feature for removing a node from my implementation in Tib TS since there I did not use useQuery which creates an issue for this feature. The rest is there though.

2024-10-21 14:53 UTC, Pooya-Oladazimi commented on src/app/types.ts
My new linter automatically format this ts file. This is the reason behind these large changes,

2024-10-22 09:19 UTC, jusa3 commented
Very nice implementation, it's fun to play around with the moving badges.
I noticed the following (not all of these may be important and need to be fixed in the prototype):
- The root walk is only a parameter in the storybook. Would it be nice to have it as a button next to the reset button?
- Would be nice to have the loading spinner a bit more central or bigger beside the icon - I didn't see it at first and wondered why nothing happened. Same with the error message 
- If I have a long path to the root (e.g. 12 nodes), I can't get them positioned properly in the graph view window. They sort of arrange themselves into a big curve that doesn't fit into the graph view window box. But I guess that's a limitation of the design library and the tree view is better for this kind of use case.
![image](https://github.com/user-attachments/assets/4397fd94-c52c-4f1a-ace1-c25d7cbf144c)
- For EFO diabetes mellitus and the SemLookP API:
testLabel instead of diabetes mellitus (happens when switching between rootWalk true and false, corrects itself when clicking reset)
![image](https://github.com/user-attachments/assets/44331cf7-8929-4ffa-be13-8bdc0c5421e8)
walk is wrong: a `thing` is not an endocrine disease
![image](https://github.com/user-attachments/assets/4cd91a5e-fb00-4e6a-94ec-5c1f43e9c623)
- For EFO diabetes mellitus and the EBI API, `thing` is not present.
![image](https://github.com/user-attachments/assets/230f3245-c6f8-4abb-a80a-4e4e1bdfbe17)
- If part of the graph (I think the current entity) is outside the window, resetting sometimes causes the graph to disappear (you have to scroll out to find it again). Perhaps resetting could also centre the current entity. 
- Water story for Chebi is missing (http://purl.obolibrary.org/obo/CHEBI_15377)
- Help menu items have different indentations
![Screenshot from 2024-10-22 11-11-48](https://github.com/user-attachments/assets/c2543bb2-59e3-449b-9067-2a9c7734b09e)

2024-10-22 10:22 UTC, Pooya-Oladazimi commented
@jusa3 

Thanks for the extensive review. I forgot to make this pr a draft since it is still in dev due to the newly requested features.

- Yes, one of the concern is that the graph becomes a long snake if the root is far away from the target node. I need to check how I can play around with the graph config to make it take less space.
- The rest of the points are not finished as I need to differentiate between the normal graph call and the ancestor call to find the walk path from the root.

2024-10-23 11:35 UTC, Pooya-Oladazimi commented
@rombaum @jusa3 

This is ready for testing and review.

2024-10-23 13:01 UTC, jusa3 commented
Very nice and quick implementation :)

Some feedback (on general usability):
- Colouring the current entity differently to improve visibility (especially in root walk) could be a nice feature. Perhaps the use of colours for different relationships in general.
- The information/instructions on how to use the graph could be a bit more styled. May as a [EuiPopover](https://eui.elastic.co/#/layout/popover)?
- As a user, I would be a bit overloaded with a long root walk. It looks rather messy to me. The filter for different relationships might solve that.
![image](https://github.com/user-attachments/assets/4ee918a0-dff0-42a0-a893-e52babec9dbe)

2024-10-23 13:47 UTC, Pooya-Oladazimi commented
@jusa3 

Thanks. The first two points, I agree. I will implement those.
Regarding, the third part, all the relations in the root walk are the same (is-a) and therefore not possible to filter.

2024-10-24 04:26 UTC, jusa3 commented
Haha, you're right about the third point and the "water" example. In this case, I think that this type of graph does a good job of representing the complex relationships of water.

2024-10-24 09:53 UTC, Pooya-Oladazimi commented
@jusa3 

Changes have been implemented.

2024-10-24 10:21 UTC, jusa3 requested changes
Just a small spelling error. Otherwise ready to go.

I also removed the graph view issue that would have been closed by this PR. Some of the CHEBI requirements mentioned there aren't implemented yet.

2024-10-24 10:21 UTC, jusa3 commented on src/components/widgets/GraphViewWidget/GraphViewWidget.tsx
> +         Guid me
Guide me

2024-10-24 10:40 UTC, Pooya-Oladazimi commented on src/components/widgets/GraphViewWidget/GraphViewWidget.tsx
> +         Guid me
Thanks. Fix has been committed.

2024-10-24 11:08 UTC, jusa3 approved these changes

2024-10-28 13:36 UTC, merged

2024-10-28 13:37 UTC, jusa3 commented
:tada: This PR is included in version 2.12.0 :tada:

The release is available on:
- [GitHub release](https://github.com/ts4nfdi/terminology-service-suite/releases/tag/v2.12.0)
- `npm package (@latest dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: