ResourcesWidget Logos and details toggle
ts4nfdi/terminology-service-suite pull request #164
Opened 2024-11-14 14:38 UTC by jusa3

- Solves https://github.com/ts4nfdi/terminology-service-suite/issues/114 (Logos)
- Adds details to toggle with homepage url, IRI and license information (only available in OLS4 V2 and thus without parameter) -> still waiting for a fix https://github.com/zbmed/semlookp-ui/issues/9
- Removes link from short form and adds it to Resource Name (leads to our terminology page)

![image](https://github.com/user-attachments/assets/3682dedb-49a9-4c7f-b0eb-cb05727e544d)

2025-01-23 12:37 UTC, rombaum requested changes

2025-01-23 12:37 UTC, rombaum commented on src/components/widgets/ResourcesWidget/ResourcesWidget.tsx
>      targetLink,
Do we still need the targetLink? I think it was replaced with the onNavigate function, or?

2025-01-23 12:37 UTC, rombaum commented on src/components/widgets/ResourcesWidget/ResourcesWidget.tsx
> +      let iri = null
What does IRI mean in this context? In some cases it is the namespace [1] in other it is the path to the ontology file [2]. I would suggest to remove it from the table.

[1]  
![grafik](https://github.com/user-attachments/assets/7b4c1a31-7369-4e95-9eee-0725ce16f876)


[2]
![grafik](https://github.com/user-attachments/assets/2e0130c7-c6ae-4e8e-9cd2-3b8209333977)

2025-01-23 12:50 UTC, rombaum commented on src/components/widgets/ResourcesWidget/ResourcesWidget.tsx
>      targetLink,
It should be solved through the PR https://github.com/ts4nfdi/terminology-service-suite/pull/185? correct?

2025-01-29 07:39 UTC, jusa3 commented on src/components/widgets/ResourcesWidget/ResourcesWidget.tsx
> +      let iri = null
You're right, the json response is different for the terminologies/APIs. Removed it.

2025-01-29 09:44 UTC, merged

2025-01-29 09:45 UTC, jusa3 commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/ts4nfdi/terminology-service-suite/releases/tag/v3.3.0)
- `npm package (@latest dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: