Feat/iri widget enhancement
ts4nfdi/terminology-service-suite pull request #86
Opened 2024-05-08 09:07 UTC by Pooya-Oladazimi

Related to https://github.com/ts4nfdi/terminology-service-suite/issues/84

Added Features:
- Make the external link icon optional. Default True.
- Added a copy to the clipboard button for the iri link. Default False.
- Added URL prefix feature for iri. When given, the encoded iri gets appended to the prefix. 
- Added stories for the above features.

2024-05-08 11:42 UTC, jusa3 requested changes
Nice new features! Please also add stories to the HTML Storybook, by exporting them in the IriWdgetHTML.stories.ts. I will adapt the readme and make it more clear for developers to update both, the React and html stories (#88)

And please merge the latest changes I made on the main branch, since this will activate the build check for pull requests. Thank you :)

2024-05-08 11:42 UTC, jusa3 commented on src/app/types.ts
> +     * Indicates that the target is exteranl and needs an icon.
spelling mistake

2024-05-08 15:21 UTC, Pooya-Oladazimi commented
Not ready yet. The new features do not work in the HTML version for some unknown reason. The stories are there but the input props have no effect.

2024-05-16 08:37 UTC, jusa3 approved these changes

2024-05-16 08:55 UTC, Pooya-Oladazimi commented on src/app/types.ts
> +    externalIcon?: string;
Yes true. I can't remember why I set it to string. I will do a fix-commit for this.

2024-05-16 10:35 UTC, jusa3 approved these changes

2024-05-16 11:10 UTC, merged

2024-05-16 11:12 UTC, jusa3 commented
:tada: This PR is included in version 2.0.3 :tada:

The release is available on:
- [GitHub release](https://github.com/ts4nfdi/terminology-service-suite/releases/tag/v2.0.3)
- `npm package (@latest dist-tag)`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: